### ISSUE TITLE
Documentation pages

### ISSUE THREAD

**Issue by dasv74** [splineops/splineops#25]
**Home page**
- Reference papers: provide a list of the major papers on spline of the BIG with the agreement of the authors
- PDF: may be provide the PDF of the major papers with the agreement of the authors

**Installation**
- Indicate the minimum required version of Python (3.10)

**Example 2D rotation of image**
- The links "Lite" and "Binder" could open a new tab in the browser

- The right box is disappearing when the window is small
 On this page
	Imports
	Helper functions
	Load and preprocess image
	Create animation
 	Download source code
 	Download Jupyter notebook
	Launch JupyterLite
	Launch binder
	
- Binder run for ever

- Lite starts quickly but the first cell with the error:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 7
      4 from IPython.display import HTML, display
      5 from matplotlib import animation
----> 7 from splineops.interpolate.tensorspline import TensorSpline

ModuleNotFoundError: No module named 'splineops'

**Comment by dperdios** [comment]
It's a multi-issue issue but most important point that should be fixed asap is the fact that neither Lite nor Binder setups enables running the examples.

@pagarcia I guess this should be somehow easy to fix right? For Lite it seems like the `splineops` is simply not installed in the environment

**Comment by pagarcia** [comment]
Yes I'm working on this. I fixed binder issue within the feature/binder-fix branch https://github.com/splineops/splineops/tree/feature/binder-fix, will soon make a PR.

For Lite it seems it may just not be possible as our package is not part of an environment called Pyodide.
See in https://sphinx-gallery.github.io/stable/configuration.html#jupyterlite
"with JupyterLite environments are not as flexible as Binder, for example you can not use a docker image but only the default [Pyodide](https://pyodide.org/en/stable/index.html) environment. That means that some non pure-Python packages may not be available, see list of [available packages in Pyodide](https://pyodide.org/en/stable/usage/packages-in-pyodide.html)."

In which case I will just hide the JupyterLite button until this has progressed.

**Comment by dperdios** [comment]
Awesome and thanks for the references!

Yes that's fine to hide whatever is not possible yet 👍

**Comment by pagarcia** [comment]
Fixed these issues in PR https://github.com/splineops/splineops/pull/29, except the one of

_The right box is disappearing when the window is small
On this page
Imports
Helper functions
Load and preprocess image
Create animation
Download source code
Download Jupyter notebook
Launch JupyterLite
Launch binder_

which requires more careful investigation and understanding of what should happen and is actually happening.

**Comment by pagarcia** [comment]
Fixed in PR #29
