### ISSUE TITLE
Revise copyright terminology on github.io

### ISSUE THREAD

**Issue by dperdios** [splineops/splineops#26]
© Copyright 2021 - 2024, SplineOps developers (BSD 3-Clause License).

The BSD license is for the code of the Python package not for the documentation / github.io. As many other packages (https://pylops.readthedocs.io/en/stable/; https://jax.readthedocs.io/en/latest/; etc.), we should only have:

© Copyright 2024, SplineOps authors.

**Comment by pagarcia** [comment]
Fixed in commit https://github.com/splineops/splineops/commit/041e61d81cee8f7b19d7b2b38d25882ca5bcf4f5.
