### ISSUE TITLE
Erroneous version number in title of github.io

### ISSUE THREAD

**Issue by dperdios** [splineops/splineops#27]
The title shows splineops version 0.0.1

<img width="1175" alt="Screenshot 2024-09-17 at 17 59 40" src="https://github.com/user-attachments/assets/940b4bc7-2e55-4caa-8ac2-1f82b889e7b4">

**Comment by pagarcia** [comment]
Addressed in commit https://github.com/splineops/splineops/commit/db85cf030d529e8ab857202c68033a03bc4e7782.

**Comment by pagarcia** [comment]
Fixed in PR https://github.com/splineops/splineops/pull/29
